name: Azure MLOps CI/CD Simulation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  mlops-simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model (Simulate Azure Compute)
        run: |
          python train_to_azure.py

      - name: Deploy model (Simulate Azure Endpoint)
        run: |
          python deploy_azure_model.py

      - name: Monitor deployment (Simulate Azure Monitor)
        run: |
          python monitor_azure.py